/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Visitor } from "./Visitor";
import { VisitorCountArgs } from "./VisitorCountArgs";
import { VisitorFindManyArgs } from "./VisitorFindManyArgs";
import { VisitorFindUniqueArgs } from "./VisitorFindUniqueArgs";
import { CreateVisitorArgs } from "./CreateVisitorArgs";
import { UpdateVisitorArgs } from "./UpdateVisitorArgs";
import { DeleteVisitorArgs } from "./DeleteVisitorArgs";
import { VisitLogFindManyArgs } from "../../visitLog/base/VisitLogFindManyArgs";
import { VisitLog } from "../../visitLog/base/VisitLog";
import { VisitorService } from "../visitor.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Visitor)
export class VisitorResolverBase {
  constructor(
    protected readonly service: VisitorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "read",
    possession: "any",
  })
  async _visitorsMeta(
    @graphql.Args() args: VisitorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Visitor])
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "read",
    possession: "any",
  })
  async visitors(
    @graphql.Args() args: VisitorFindManyArgs
  ): Promise<Visitor[]> {
    return this.service.visitors(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Visitor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "read",
    possession: "own",
  })
  async visitor(
    @graphql.Args() args: VisitorFindUniqueArgs
  ): Promise<Visitor | null> {
    const result = await this.service.visitor(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Visitor)
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "create",
    possession: "any",
  })
  async createVisitor(
    @graphql.Args() args: CreateVisitorArgs
  ): Promise<Visitor> {
    return await this.service.createVisitor({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Visitor)
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "update",
    possession: "any",
  })
  async updateVisitor(
    @graphql.Args() args: UpdateVisitorArgs
  ): Promise<Visitor | null> {
    try {
      return await this.service.updateVisitor({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Visitor)
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "delete",
    possession: "any",
  })
  async deleteVisitor(
    @graphql.Args() args: DeleteVisitorArgs
  ): Promise<Visitor | null> {
    try {
      return await this.service.deleteVisitor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Visitor)
  async uploadCapturedImage(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: VisitorFindUniqueArgs
  ): Promise<Visitor> {
    return await this.service.uploadCapturedImage(args, file);
  }

  @graphql.Mutation(() => Visitor)
  async deleteCapturedImage(
    @graphql.Args()
    args: VisitorFindUniqueArgs
  ): Promise<Visitor> {
    return await this.service.deleteCapturedImage(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [VisitLog], { name: "visitLogs" })
  @nestAccessControl.UseRoles({
    resource: "VisitLog",
    action: "read",
    possession: "any",
  })
  async findVisitLogs(
    @graphql.Parent() parent: Visitor,
    @graphql.Args() args: VisitLogFindManyArgs
  ): Promise<VisitLog[]> {
    const results = await this.service.findVisitLogs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
